name: Java

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
        
      - name: Build
        run: mvn --batch-mode -DskipTests package
        
        
      - name: Login to Docker HuB
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -P $DOCKER_PASSWORD
        
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ypeng23/homework:latest
        
       

      
